---
title: "EDA"
output: pdf_document
---

```{r packages}
library(tidyverse)
library(foreign)
```

```{r load-data}
generic_ballot_polls <- read.csv("data/generic_ballot_polls.csv")
governor_polls <- read.csv("data/governor_polls.csv")
house_polls <- read.csv("data/house_polls.csv")
pres_primary_avgs_2020 <- read.csv("data/pres_primary_avgs_2020.csv")
president_approval_polls <- read.csv("data/president_approval_polls.csv")
president_polls <- read.csv("data/president_polls.csv")
presidential_poll_averages_2020 <- read.csv("data/presidential_poll_averages_2020.csv") # note Maine and Nebraska are counted several times due to split electoral votes in this dataset
senate_polls <- read.csv("data/senate_polls.csv")

economist_polls <- read.csv("data/2016_Economist_Polls.csv")
state_update <- read.dta("data/state_level_update.dta")
gay_marriage <- read.dta("data/gay_marriage_megapoll.dta")

cces <- readRDS("data/cumulative_2006-2019.Rds")

census <- read.csv("data/cc-est2019-alldata-37.csv")

gay_marriage <- read.dta("data/gay_marriage_megapoll.dta")

parent_income <- read.csv("data/mrc_table12.csv")
outcomes <- read.csv("data/tract_outcomes_early.csv")

neighborhood_census <- read.csv("data/tract_covariates.csv")
neighborhood_county <- read.csv("data/cty_covariates.csv")
```


```{r approval-ratings}
president_approval_polls %>%
  ggplot(aes(x = as.Date(end_date, format = "%m/%d/%y"), y = yes)) + geom_point(aes(size = sample_size, alpha = 0.3))+ geom_smooth(color = "red")

```


```{r presidential-polls-by-state}
presidential_poll_averages_2020 %>%
  filter(state == "National") %>% ggplot(aes(x = as.Date(modeldate, format = "%m/%d/%y"), y = pct_estimate, color = candidate_name)) + geom_line() + labs(title = "National Polls") + scale_colour_manual(values = c("Joseph R. Biden Jr." = "#123adb", "Donald Trump" = "#E01414", "Convention Bounce for Donald Trump" = "#ffb2ab","Convention Bounce for Joseph R. Biden Jr." =  "#abd1ff"))

presidential_poll_averages_2020 %>%
  filter(state != "National") %>% 
  filter(state != "ME-1") %>%
  filter(state != "ME-2") %>%
  filter(state != "NE-1") %>%
  filter(state != "NE-2") %>%
  filter(candidate_name == "Donald Trump" | candidate_name == "Joseph R. Biden Jr.") %>%
  ggplot(aes(x = as.Date(modeldate, format = "%m/%d/%y"), y = pct_estimate, color = candidate_name)) + geom_line() + facet_wrap(~state) + labs(title = "Polls by state") + scale_colour_manual(values = c("Joseph R. Biden Jr." = "#123adb", "Donald Trump" = "#E01414"))

presidential_poll_averages_2020 %>%
  filter(state == "Florida" | state == "Pennsylvania" | state == "Ohio" | state == "Michigan" | state == "North Carolina" | state == "Arizona" | state == "Wisconsin" |  state == "Iowa") %>%
  filter(candidate_name == "Donald Trump" | candidate_name == "Joseph R. Biden Jr.") %>%
  ggplot(aes(x = as.Date(modeldate, format = "%m/%d/%y"), y = pct_estimate, color = candidate_name)) + geom_line() + facet_wrap(~state) + labs(title = "Polls by Swing State") + scale_colour_manual(values = c("Joseph R. Biden Jr." = "#123adb", "Donald Trump" = "#E01414"))

```


```{r senate-race-polls}
senate_polls %>%
  filter(candidate_party == "DEM" | candidate_party == "REP") %>%
  ggplot(aes(x = as.Date(end_date, format = "%m/%d/%y"), y = pct, color = candidate_party)) + geom_point() + facet_wrap(~race_id)+ labs(title = "Polls by senate races") + scale_colour_manual(values = c("DEM" = "#123adb", "REP" = "#E01414"))

senate_polls %>%
  filter(candidate_party == "DEM" | candidate_party == "REP") %>%
  filter(state == "Minnesota" | state == "Michigan" | state == "Arizona" | state == "Colorado" | state == "North Carolina" | state == "Maine" | state == "Iowa" | state == "Montana" | state == "Georgia" | state == "Kansas" | state == "South Carolina" | state == "Alabama" |state == "Alaska" |state == "Texas") %>%
  ggplot(aes(x = as.Date(end_date, format = "%m/%d/%y"), y = pct, color = candidate_party)) + geom_line() + facet_wrap(~race_id) + labs(title = "Polls by closer senate races") + scale_colour_manual(values = c("DEM" = "#123adb", "REP" = "#E01414"))
```


```{r nc-house-races}
## FIXME includes polls from long ago (see chunk below)
NC_house <- house_polls %>%
  filter(state == "North Carolina") %>%
  filter(candidate_party == "REP" | candidate_party == "DEM")

NC_house %>%
  ggplot(aes(x = as.Date(end_date, format = "%m/%d/%y"), y = pct, color = as.factor(candidate_party))) + geom_point() + facet_wrap(~seat_name) + scale_colour_manual(values = c("DEM" = "#123adb", "REP" = "#E01414"))

```

```{r nc-senate-race}
NC_senate <- senate_polls %>%
  filter(state == "North Carolina") %>%
  filter(candidate_party == "DEM" | candidate_party == "REP")

NC_senate %>%
  ggplot(aes(x = as.Date(end_date, format = "%m/%d/%y"), y = pct, color = as.factor(candidate_party))) + geom_point() + scale_colour_manual(values = c("DEM" = "#123adb", "REP" = "#E01414"))
```

```{r}
recent_NC_house = NC_house %>% 
  mutate(day=as.Date(end_date, format = "%m/%d/%y")) %>%
  filter(day >= as.Date('2019-01-01'))

recent_NC_house_dems = recent_NC_house %>% filter(candidate_party == 'DEM')

table(droplevels(recent_NC_house_dems$seat_name))
droplevels(recent_NC_house_dems[,c('seat_name', 'day')])

# 3, 8, 9, 11
district_name = 'District 3'
recent_NC_house_dems %>% 
  filter(seat_name == district_name) %>%
  ggplot(aes(x=day, y=pct)) + 
    geom_point() + 
    labs(title=district_name) + xlab('Date') + ylab('Percent') +  
    scale_colour_manual(values = c("DEM" = "#123adb", "REP" = "#E01414")) + 
    geom_hline(yintercept=50)
```

```{r}
filtered_NC_senate = NC_senate %>% 
  mutate(day = as.Date(end_date, format = "%m/%d/%y")) %>% 
  filter(candidate_party == 'DEM', day >= as.Date('2020-01-01'))

# unique(NC_senate$candidate_party)

filtered_NC_senate %>%
  ggplot(aes(x=day, y=pct)) + 
    geom_point() + 
    scale_colour_manual(values = c("DEM" = "#123adb", "REP" = "#E01414")) + 
    geom_vline(xintercept=as.Date('2020-10-06')) + 
    geom_hline(yintercept=50)
```


```{r}
voters <- readRDS("./data/ncvoter_Statewide_small.rds")
voters <- voters %>%
  mutate(race_code = as.character(race_code)) %>%
  mutate(gender_code = as.character(gender_code)) %>%
  mutate(race_code = case_when(race_code == ' ' ~ 'U', race_code != ' ' ~ race_code)) %>%
  mutate(gender_code = case_when(gender_code == ' ' ~ 'U', gender_code != ' ' ~ gender_code)) %>%
  mutate(race_code = as.factor(race_code)) %>%
  mutate(gender_code = as.factor(gender_code))
```

```{r}
captions <- c("Figure 1: The distribution of registered voters in North Carolina by race.", 
              "Figure 2: The distribution of registered voters in North Carolina by ethnicity.",
              "Figure 3: The distribution of registered voters in North Carolina by gender.",
              "Figure 4: The distribution of registered voters in North Carolina by party affiliation.")
big_caption <- "Exploratory data analysis for all of the registered voters in North Carolina. "
```

```{r fig.align="center", echo=FALSE, results=FALSE, warning=FALSE,fig.cap = big_caption, fig.subcap=captions, fig.ncol=2, fig.asp=1, out.width='.49\\linewidth'}
p1 <- ggplot(data = voters, aes(x = race_code)) + geom_bar(stat='count') + ggtitle("Distribution by Race within Registered Voters of North Carolina") + xlab("Race Encoding") + theme(plot.caption = element_text(hjust = 0.5))
p2 <- ggplot(data = voters, aes(x = ethnic_code)) + geom_bar(stat='count') + ggtitle("Distribution by Ethnicity within Registered Voters of North Carolina") + xlab("Ethnicity Encoding") + theme(plot.caption = element_text(hjust = 0.5))
p3 <- ggplot(data = voters, aes(x = gender_code)) + geom_bar(stat = 'count') + ggtitle("Distribution by Gender within Registered Voters of North Carolina") + xlab("Gender Encoding") + theme(plot.caption = element_text(hjust = 0.5))
p4 <- ggplot(data = voters, aes(x = party_cd)) + geom_bar(stat='count') + ggtitle("Distribution by Party Affiliation within Registered Voters of North Carolina") + xlab("Party Affiliation") + theme(plot.caption = element_text(hjust = 0.5))
p1
p2
p3
p4
```




