---
title: "predictions"
author: "Scott Heng"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(R2jags)
```

```{r}

pres <- read.csv(file = "data/president_polls.csv") 

pres <- pres %>% 
  mutate(days_to_election = as.Date(election_date, format="%m/%d/%y")-
                  as.Date(start_date, format="%m/%d/%y"))%>%
  filter(candidate_name == "Donald Trump" | candidate_name == "Joseph R. Biden Jr.")%>%
  mutate(days_to_election = as.numeric(days_to_election)) %>%
  filter(days_to_election <= 200)%>%
  filter(question_id != 123584 & question_id != 124133 & question_id != 124134 & question_id != 127451 & question_id != 131614 & question_id != 131615 & question_id != 133072)

pres %>%
  group_by(question_id) %>%
  count() %>%
  arrange(n)

polls_trump <- pres %>%
  filter(candidate_party=="REP") 
r_pct = polls_trump$pct

polls_biden <- pres %>%
  filter(candidate_party == "DEM")
d_pct = polls_biden$pct

polls_trump$rep_pct = 100*r_pct/(r_pct + d_pct)

```

```{r}
elec_votes <- c(3,10,5,12,13,3,6,38,11,3,9,4,
                20,7,7,18,3,15,29,5,14,4,6,5,
                0,0,0,3,10,6,10,16,11,10,4,0,
                0,8,8,6,6,11,20,4,4,16,29,0,3,
                7,9,55,6,11,3,9)
```

```{r data_list,eval=TRUE}
states <- polls_trump$state %>% unique
y <- polls_trump$rep_pct
r <- match(polls_trump$state,states)
t <- polls_trump$days_to_election + 1 #WHY PLUS ONE?
N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max
jags_data_trump <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days)

```

```{r}
model <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = beta[r[k],t[k]] 
  }
  for(j in 2:N_days){
    for(i in 1:N_states){
      beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
    }
  }
  
  #EXERCISE: add hierarhciacl prior for sigma2_beta and sigma2_y, i.e. sigma2_beta[j] all come from a common distribution 
  for(j in 1:N_states){
      sigma2_y[j] = 1/sigma2_y_inv[j]
      sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
      
      sigma2_beta[j] = 1/sigma2_beta_inv[j]
      sigma2_beta_inv[j] ~ dgamma(nu_beta,nu_beta*tau_beta) 
      
      beta[j,1] ~ dnorm(mu0,pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  mu0 ~ dnorm(50,pow(7.5,-2))
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
}
```

```{r run_model,eval=TRUE}
#be sure to add your added parameters to parameters.to.save
set.seed(2020)
jags_sims_trump <- jags(data = jags_data_trump,
                  model.file = model,
                  parameters.to.save = c("beta[1,1]",
                                                                          "beta[2,1]",
                                                                          "beta[3,1]",
                                                                          "beta[4,1]",
                                                                          "beta[5,1]",
                                                                          "beta[6,1]",
                                                                          "beta[7,1]",
                                                                          "beta[8,1]",
                                                                          "beta[9,1]",
                                                                          "beta[10,1]",
                                                                          "beta[11,1]",
                                                                          "beta[12,1]",
                                                                          "beta[13,1]",
                                                                          "beta[14,1]",
                                                                          "beta[15,1]",
                                                                          "beta[16,1]",
                                                                          "beta[17,1]",
                                                                          "beta[18,1]",
                                                                          "beta[19,1]",
                                                                          "beta[20,1]",
                                                                          "beta[21,1]",
                                                                          "beta[22,1]",
                                                                          "beta[23,1]",
                                                                          "beta[24,1]",
                                                                          "beta[25,1]",
                                                                          "beta[26,1]",
                                                                          "beta[27,1]",
                                                                          "beta[28,1]",
                                                                          "beta[29,1]",
                                                                          "beta[30,1]",
                                                                          "beta[31,1]",
                                                                          "beta[32,1]",
                                                                          "beta[33,1]",
                                                                          "beta[34,1]",
                                                                          "beta[35,1]",
                                                                          "beta[36,1]",
                                                                          "beta[37,1]",
                                                                          "beta[38,1]",
                                                                          "beta[39,1]",
                                                                          "beta[40,1]",
                                                                          "beta[41,1]",
                                                                          "beta[42,1]",
                                                                          "beta[43,1]",
                                                                          "beta[44,1]",
                                                                          "beta[45,1]",
                                                                          "beta[46,1]",
                                                                          "beta[47,1]",
                                                                          "beta[48,1]",
                                                                          "beta[49,1]",
                                                                          "beta[50,1]",
                                         "beta[51,1]",
                                         "beta[52,1]",
                                         "beta[53,1]",
                                         "beta[54,1]",
                                         "beta[55,1]",
                                         "beta[56,1]"),
                  n.iter = 1000)
```

<!-- 2020 sims -->
```{r}
#trump
jags_r <- jags_sims_trump
b1r <- jags_r$BUGSoutput$sims.array[1:1500]
b10r <- jags_r$BUGSoutput$sims.array[1501:3000]
b11r <- jags_r$BUGSoutput$sims.array[3001:4500]
b12r <- jags_r$BUGSoutput$sims.array[4501:6000]
b13r <- jags_r$BUGSoutput$sims.array[6001:7500]
b14r <- jags_r$BUGSoutput$sims.array[7501:9000]
b15r <- jags_r$BUGSoutput$sims.array[9001:10500]
b16r <- jags_r$BUGSoutput$sims.array[10501:12000]
b17r <- jags_r$BUGSoutput$sims.array[12001:13500]
b18r <- jags_r$BUGSoutput$sims.array[13501:15000]
b19r <- jags_r$BUGSoutput$sims.array[15001:16500]
b2r <- jags_r$BUGSoutput$sims.array[16501:18000]
b20r <- jags_r$BUGSoutput$sims.array[18001:19500]
b21r <- jags_r$BUGSoutput$sims.array[19501:21000]
b22r <- jags_r$BUGSoutput$sims.array[21001:22500]
b23r <- jags_r$BUGSoutput$sims.array[22501:24000]
b24r <- jags_r$BUGSoutput$sims.array[24001:25500]
b25r <- jags_r$BUGSoutput$sims.array[25501:27000]
b26r <- jags_r$BUGSoutput$sims.array[27001:28500]
b27r <- jags_r$BUGSoutput$sims.array[28501:30000]
b28r <- jags_r$BUGSoutput$sims.array[30001:31500]
b29r <- jags_r$BUGSoutput$sims.array[31501:33000]
b3r <- jags_r$BUGSoutput$sims.array[33001:34500]
b30r <- jags_r$BUGSoutput$sims.array[34501:36000]
b31r <- jags_r$BUGSoutput$sims.array[36001:37500]
b32r <- jags_r$BUGSoutput$sims.array[37501:39000]
b33r <- jags_r$BUGSoutput$sims.array[39001:40500]
b34r <- jags_r$BUGSoutput$sims.array[40501:42000]
b35r <- jags_r$BUGSoutput$sims.array[42001:43500]
b36r <- jags_r$BUGSoutput$sims.array[43501:45000]
b37r <- jags_r$BUGSoutput$sims.array[45001:46500]
b38r <- jags_r$BUGSoutput$sims.array[48001:49500]
b39r <- jags_r$BUGSoutput$sims.array[49501:51000]
b4r <- jags_r$BUGSoutput$sims.array[51001:52500]
b40r <- jags_r$BUGSoutput$sims.array[52501:54000]
b41r <- jags_r$BUGSoutput$sims.array[54001:55500]
b42r <- jags_r$BUGSoutput$sims.array[55501:57000]
b43r <- jags_r$BUGSoutput$sims.array[57001:58500]
b44r <- jags_r$BUGSoutput$sims.array[58501:60000]
b45r <- jags_r$BUGSoutput$sims.array[60001:61500]
b46r <- jags_r$BUGSoutput$sims.array[61501:63000]
b47r <- jags_r$BUGSoutput$sims.array[63001:64500]
b48r <- jags_r$BUGSoutput$sims.array[64501:66000]
b49r <- jags_r$BUGSoutput$sims.array[66001:67500]
b5r <- jags_r$BUGSoutput$sims.array[69001:70500]
b50r <- jags_r$BUGSoutput$sims.array[70501:72000]
b51r <- jags_r$BUGSoutput$sims.array[72001:73500]
b52r <- jags_r$BUGSoutput$sims.array[73501:75000]
b53r <- jags_r$BUGSoutput$sims.array[75001:76500]
b54r <- jags_r$BUGSoutput$sims.array[76501:78000]
b55r <- jags_r$BUGSoutput$sims.array[78001:79500]
b56r <- jags_r$BUGSoutput$sims.array[79501:81000]
b6r <- jags_r$BUGSoutput$sims.array[81001:82500]
b7r <- jags_r$BUGSoutput$sims.array[82501:84000]
b8r <- jags_r$BUGSoutput$sims.array[84001:85500]
b9r <- jags_r$BUGSoutput$sims.array[85501:87000]

w1 = ifelse(b1r > 50, 6, 0) #IA
w2 = ifelse(b2r > 50, 20, 0) #PA
w3 = ifelse(b3r > 50, 0, 0) #national
w4 = ifelse(b4r > 50, 11, 0) # AZ
w5 = ifelse(b5r > 50, 16, 0) # GA
w6 = ifelse(b6r > 50, 20, 0) # IL
w7 = ifelse(b7r > 50, 16, 0) # MI
w8 = ifelse(b8r > 50, 10, 0) # MN
w9 = ifelse(b9r > 50, 14, 0) # NJ
w10 = ifelse(b10r > 50, 29, 0) # NY
w11 = ifelse(b11r > 50, 18, 0) # OH
w12 = ifelse(b12r > 50, 10, 0) # WI
w13 = ifelse(b13r > 50, 29, 0) # FL
w14 = ifelse(b14r > 50, 9, 0) # CO
w15 = ifelse(b15r > 50, 55, 0) # CA
w16 = ifelse(b16r > 50, 15, 0) # NC
w17 = ifelse(b17r > 50, 38, 0) # TX
w18 = ifelse(b18r > 50, 13, 0) # VA
w19 = ifelse(b19r > 50, 9, 0) # AL
w20 = ifelse(b20r > 50, 3, 0) # WY
w21 = ifelse(b21r > 50, 5, 0) # WV 
w22 = ifelse(b22r > 50, 12, 0) # WA
w23 = ifelse(b23r > 50, 3, 0) # VT
w24 = ifelse(b24r > 50, 6, 0) # UT
w25 = ifelse(b25r > 50, 11, 0) # TN
w26 = ifelse(b26r > 50, 3, 0) # SD
w27 = ifelse(b27r > 50, 9, 0) # SC
w28 = ifelse(b28r > 50, 4, 0) # RI
w29 = ifelse(b29r > 50, 7, 0) # OR
w30 = ifelse(b30r > 50, 7, 0) # OK
w31 = ifelse(b31r > 50, 6, 0) # NV
w32 = ifelse(b32r > 50, 5, 0) # NM
w33 = ifelse(b33r > 50, 4, 0) # NH
w34 = ifelse(b34r > 50, 5, 0) # NE
w35 = ifelse(b35r > 50, 3, 0) # ND
w36 = ifelse(b36r > 50, 3, 0) # MT
w37 = ifelse(b37r > 50, 6, 0) # MS
w38 = ifelse(b38r > 50, 10, 0) # MO
w39 = ifelse(b39r > 50, 4, 0) # ME
w40 = ifelse(b40r > 50, 10, 0) # MD
w41 = ifelse(b41r > 50, 11, 0) # MA
w42 = ifelse(b42r > 50, 8, 0) # LA
w43 = ifelse(b43r > 50, 8, 0) # KY
w44 = ifelse(b44r > 50, 6, 0) # KS
w45 = ifelse(b45r > 50, 11, 0) # IN
w46 = ifelse(b46r > 50, 4, 0) # ID
w47 = ifelse(b47r > 50, 4, 0) # HI
w48 = ifelse(b48r > 50, 3, 0) # DE
w49 = ifelse(b49r > 50, 3, 0) # DC
w50 = ifelse(b50r > 50, 7, 0) # CT
w51 = ifelse(b51r > 50, 6, 0) # AR
w52 = ifelse(b52r > 50, 3, 0) # AK
w53 = ifelse(b53r > 50, 0, 0) # ME CD-1
w54 = ifelse(b54r > 50, 0, 0) # ME CD-2
w55 = ifelse(b55r > 50, 0, 0) # NE CD-2
w56 = ifelse(b56r > 50, 0, 0) # NE CD-1

r_wins <- data.frame(cbind(w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31,w32,w33,w34,w35,w36,w37,w38,w39,w40,w41,w42,w43,w44,w45,w46,w47,w48,w49,w50,w51,w52,w53,w54,w55,w56))

n = nrow(r_wins)

r_wins$total = rowSums(r_wins)

trump_electoral <- r_wins%>%
  filter(total > 269) %>%
  summarise(perc = n()/nrow(r_wins)) %>%
  pull()

trump_electoral

```

<!-- 2016 stuff -->
```{r}
set.seed(2016)
polls <- read_csv("data/2016_Economist_Polls.csv") %>% 
  filter(population %in% c("Likely Voters","Registered Voters"),question.iteration == 1) %>% #remove duplicate questions
  mutate(days_to_election = ifelse(end.date == "11/7/16", 1, ifelse(end.date == "11/6/16",2, ifelse(end.date == "11/5/16",3,101))),
         state = ifelse(state == "--","US",state),
         y = clinton/(clinton + trump)*100)

polls <- polls %>%
  filter(days_to_election <= 100)

states <- polls$state %>% unique
y <- polls$y
r <- match(polls$state,states)
t <- polls$days_to_election + 1 #WHY PLUS ONE?
N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max
jags_data <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days)

model <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = beta[r[k],t[k]] 
  }
  for(j in 2:N_days){
    for(i in 1:N_states){
      beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
    }
  }
  
  #EXERCISE: add hierarhciacl prior for sigma2_beta and sigma2_y, i.e. sigma2_beta[j] all come from a common distribution 
  for(j in 1:N_states){
      sigma2_y[j] = 1/sigma2_y_inv[j]
      sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
      
      sigma2_beta[j] = 1/sigma2_beta_inv[j]
      sigma2_beta_inv[j] ~ dgamma(nu_beta,nu_beta*tau_beta) 
      
      beta[j,1] ~ dnorm(mu0,pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  mu0 ~ dnorm(50,pow(7.5,-2))
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
}

jags_r <- jags(data = jags_data,model.file = model,parameters.to.save = c("beta[1,1]",
                                                                          "beta[2,1]",
                                                                          "beta[3,1]",
                                                                          "beta[4,1]",
                                                                          "beta[5,1]",
                                                                          "beta[6,1]",
                                                                          "beta[7,1]",
                                                                          "beta[8,1]",
                                                                          "beta[9,1]",
                                                                          "beta[10,1]",
                                                                          "beta[11,1]",
                                                                          "beta[12,1]",
                                                                          "beta[13,1]",
                                                                          "beta[14,1]",
                                                                          "beta[15,1]",
                                                                          "beta[16,1]",
                                                                          "beta[17,1]",
                                                                          "beta[18,1]",
                                                                          "beta[19,1]",
                                                                          "beta[20,1]",
                                                                          "beta[21,1]",
                                                                          "beta[22,1]",
                                                                          "beta[23,1]",
                                                                          "beta[24,1]",
                                                                          "beta[25,1]",
                                                                          "beta[26,1]",
                                                                          "beta[27,1]",
                                                                          "beta[28,1]",
                                                                          "beta[29,1]",
                                                                          "beta[30,1]",
                                                                          "beta[31,1]",
                                                                          "beta[32,1]",
                                                                          "beta[33,1]",
                                                                          "beta[34,1]",
                                                                          "beta[35,1]",
                                                                          "beta[36,1]",
                                                                          "beta[37,1]",
                                                                          "beta[38,1]",
                                                                          "beta[39,1]",
                                                                          "beta[40,1]",
                                                                          "beta[41,1]",
                                                                          "beta[42,1]",
                                                                          "beta[43,1]",
                                                                          "beta[44,1]",
                                                                          "beta[45,1]",
                                                                          "beta[46,1]",
                                                                          "beta[47,1]",
                                                                          "beta[48,1]",
                                                                          "beta[49,1]",
                                                                          "beta[50,1]",
                                                                          "beta[51,1]",
                                                                          "sigma2_beta",
                                                                             "p","sigma2_y"),
                  n.iter = 1000)
```



```{r}
jags_r$BUGSoutput
```


```{r}
elec_votes_r <- c(9,9,3,6,11,55,9,7,3,29,16,4,4,20,11,6,8,8,4,10,11,16,10,6,10,3,15,3,4,14,5,6,6,29,3,18,7,7,20,4,9,3,11,38,6,13,3,12,10,5,3)

b1r <- jags_r$BUGSoutput$sims.array[1:1500]
b10r <- jags_r$BUGSoutput$sims.array[1501:3000]
b11r <- jags_r$BUGSoutput$sims.array[3001:4500]
b12r <- jags_r$BUGSoutput$sims.array[4501:6000]
b13r <- jags_r$BUGSoutput$sims.array[6001:7500]
b14r <- jags_r$BUGSoutput$sims.array[7501:9000]
b15r <- jags_r$BUGSoutput$sims.array[9001:10500]
b16r <- jags_r$BUGSoutput$sims.array[10501:12000]
b17r <- jags_r$BUGSoutput$sims.array[12001:13500]
b18r <- jags_r$BUGSoutput$sims.array[13501:15000]
b19r <- jags_r$BUGSoutput$sims.array[15001:16500]
b2r <- jags_r$BUGSoutput$sims.array[16501:18000]
b20r <- jags_r$BUGSoutput$sims.array[18001:19500]
b21r <- jags_r$BUGSoutput$sims.array[19501:21000]
b22r <- jags_r$BUGSoutput$sims.array[21001:22500]
b23r <- jags_r$BUGSoutput$sims.array[22501:24000]
b24r <- jags_r$BUGSoutput$sims.array[24001:25500]
b25r <- jags_r$BUGSoutput$sims.array[25501:27000]
b26r <- jags_r$BUGSoutput$sims.array[27001:28500]
b27r <- jags_r$BUGSoutput$sims.array[28501:30000]
b28r <- jags_r$BUGSoutput$sims.array[30001:31500]
b29r <- jags_r$BUGSoutput$sims.array[31501:33000]
b3r <- jags_r$BUGSoutput$sims.array[33001:34500]
b30r <- jags_r$BUGSoutput$sims.array[34501:36000]
b31r <- jags_r$BUGSoutput$sims.array[36001:37500]
b32r <- jags_r$BUGSoutput$sims.array[37501:39000]
b33r <- jags_r$BUGSoutput$sims.array[39001:40500]
b34r <- jags_r$BUGSoutput$sims.array[40501:42000]
b35r <- jags_r$BUGSoutput$sims.array[42001:43500]
b36r <- jags_r$BUGSoutput$sims.array[43501:45000]
b37r <- jags_r$BUGSoutput$sims.array[45001:46500]
b38r <- jags_r$BUGSoutput$sims.array[48001:49500]
b39r <- jags_r$BUGSoutput$sims.array[49501:51000]
b4r <- jags_r$BUGSoutput$sims.array[51001:52500]
b40r <- jags_r$BUGSoutput$sims.array[52501:54000]
b41r <- jags_r$BUGSoutput$sims.array[54001:55500]
b42r <- jags_r$BUGSoutput$sims.array[55501:57000]
b43r <- jags_r$BUGSoutput$sims.array[57001:58500]
b44r <- jags_r$BUGSoutput$sims.array[58501:60000]
b45r <- jags_r$BUGSoutput$sims.array[60001:61500]
b46r <- jags_r$BUGSoutput$sims.array[61501:63000]
b47r <- jags_r$BUGSoutput$sims.array[63001:64500]
b48r <- jags_r$BUGSoutput$sims.array[64501:66000]
b49r <- jags_r$BUGSoutput$sims.array[66001:67500]
b5r <- jags_r$BUGSoutput$sims.array[69001:70500]
b50r <- jags_r$BUGSoutput$sims.array[70501:72000]
b51r <- jags_r$BUGSoutput$sims.array[72001:73500]

w1 = ifelse(b1r > 50, 0, 0) # US
w2 = ifelse(b2r > 50, 3, 0) # AK
w3 = ifelse(b3r > 50, 9, 0) # AL
w4 = ifelse(b4r > 50, 11, 0) # AR
w5 = ifelse(b5r > 50, 6, 0) # AZ
w6 = ifelse(b6r > 50, 55, 0) # CA
w7 = ifelse(b7r > 50, 9, 0) # CO
w8 = ifelse(b8r > 50, 7, 0) # CT
w9 = ifelse(b9r > 50, 3, 0) # DE
w10 = ifelse(b10r > 50, 29, 0) # FL
w11 = ifelse(b11r > 50, 16, 0) # GA
w12 = ifelse(b12r > 50, 4, 0) # HI
w13 = ifelse(b13r > 50, 6, 0) # IA
w14 = ifelse(b14r > 50, 4, 0) # ID
w15 = ifelse(b15r > 50, 20, 0) # IL
w16 = ifelse(b16r > 50, 11, 0) # IN
w17 = ifelse(b17r > 50, 6, 0) # KS
w18 = ifelse(b18r > 50, 8, 0) # KY
w19 = ifelse(b19r > 50, 8, 0) # LA
w20 = ifelse(b20r > 50, 11, 0) # MA
w21 = ifelse(b21r > 50, 10, 0) # MD
w22 = ifelse(b22r > 50, 4, 0) # ME
w23 = ifelse(b23r > 50, 16, 0) # MI
w24 = ifelse(b24r > 50, 10, 0) # MN
w25 = ifelse(b25r > 50, 10, 0) # MO
w26 = ifelse(b26r > 50, 6, 0) # MS 
w27 = ifelse(b27r > 50, 3, 0) # MT
w28 = ifelse(b28r > 50, 15, 0) # NC
w29 = ifelse(b29r > 50, 3, 0) # ND
w30 = ifelse(b30r > 50, 5, 0) # NE
w31 = ifelse(b31r > 50, 4, 0) # NH
w32 = ifelse(b32r > 50, 14, 0) # NJ
w33 = ifelse(b33r > 50, 5, 0) # NM
w34 = ifelse(b34r > 50, 6, 0) # NV
w35 = ifelse(b35r > 50, 29, 0) # NY
w36 = ifelse(b36r > 50, 18, 0) # OH
w37 = ifelse(b37r > 50, 7, 0) # OK
w38 = ifelse(b38r > 50, 7, 0) # OR
w39 = ifelse(b39r > 50, 20, 0) # PA
w40 = ifelse(b40r > 50, 4, 0) # RI
w41 = ifelse(b41r > 50, 9, 0) # SC
w42 = ifelse(b42r > 50, 3, 0) # SD
w43 = ifelse(b43r > 50, 11, 0) # TN
w44 = ifelse(b44r > 50, 38, 0) # TX
w45 = ifelse(b45r > 50, 6, 0) # UT
w46 = ifelse(b46r > 50, 13, 0) # VA
w47 = ifelse(b47r > 50, 3, 0) # VT
w48 = ifelse(b48r > 50, 12, 0) # WA
w49 = ifelse(b49r > 50, 10, 0) # WI
w50 = ifelse(b50r > 50, 5, 0) # WV
w51 = ifelse(b51r > 50, 3, 0) # WY

r_wins <- data.frame(cbind(w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31,w32,w33,w34,w35,w36,w37,w38,w39,w40,w41,w42,w43,w44,w45,w46,w47,w48,w49,w50,w51))

n = nrow(r_wins)

r_wins$total = rowSums(r_wins)

clinton_electoral <- r_wins%>%
  filter(total > 269) %>%
  summarise(perc = n()/nrow(r_wins)) %>%
  pull()

clinton_electoral
```


## Traceplots
    
```{r, echo = FALSE, message=FALSE, warning=FALSE, include=FALSE}
# run traceplots
parameters = c(names(data.frame(jags_sims_trump$BUGSoutput$sims.matrix)))[1:5]

res = data.frame(jags_sims_trump$BUGSoutput$sims.matrix)[,parameters]

tps <- function(var){
  ggplot(res, aes_(y=as.name(var), x=seq(1,nrow(res)))) +
    geom_line() +
    labs(title=paste("Traceplot of ", as.name(var)),
         x ="Iterations", y = as.name(var))
}
lapply(names(res), tps)
```

## Lag-1 Scatterplots

```{r, echo = FALSE, message=FALSE, warning=FALSE}
# run lag-1 scatterplots
library(ggplot2)
res_lag1 = lapply(seq(1:length(res)), function(i) {
  lres = lag(res[,i],1)
  plot(y=res[,i], x= lres, 
       xlab = paste0(colnames(res)[i], "-1"),
       ylab = paste0(colnames(res)[i]),
       main = paste("Lag-1 Scatter Plot of", colnames(res)[i]))
})
```

## ACF plots

```{r, echo = F, message=FALSE, warning=FALSE}
# run acf plots
lapply(seq(1,length(res)), function(i) { 
  acf(res[,i], xlab = "Lag", ylab = "ACF", 
            main = paste("ACF Plot of ", colnames(res)[i]))
})
```

```{r}
jags_sims_trump$BUGSoutput
```