---
title: "senate_predictions"
author: "Ashley Murray"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(tidyverse)
library(R2jags)
```

```{r}
senate_polls <- read.csv(file='data/senate_polls.csv')
senate_polls <- senate_polls %>%
  mutate(days_to_election = as.Date(as.character(election_date), format ="%m/%d/%Y")-as.Date(as.character(start_date), format = "%m/%d/%Y"))

polls_republican <- senate_polls %>%
  filter(candidate_party=="REP")
polls_not_republican <- senate_polls %>%
  filter(candidate_party != "REP")
```

```{r}
states <- polls_republican$state %>% unique
y <- polls_republican$pct_estimate
r <- match(polls_republican$state,states)
t <- polls_republican$days_to_election + 1 #WHY PLUS ONE?
N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max
jags_data_republican <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days)



states <- polls_not_republican$state %>% unique
y <- polls_not_republican$pct
r <- match(polls_not_republican$state,states)
t <- polls_not_republican$days_to_election + 1 #WHY PLUS ONE?
N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max
jags_data_not_republican <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days)
```

```{r}
model <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = beta[r[k],t[k]] 
  }
  for(j in 2:N_days){
    for(i in 1:N_states){
      beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
    }
  }
  
  #EXERCISE: add hierarhciacl prior for sigma2_beta and sigma2_y, i.e. sigma2_beta[j] all come from a common distribution 
  for(j in 1:N_states){
      sigma2_y[j] = 1/sigma2_y_inv[j]
      sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
      
      sigma2_beta[j] = 1/sigma2_beta_inv[j]
      sigma2_beta_inv[j] ~ dgamma(nu_beta,nu_beta*tau_beta) 
      
      beta[j,1] ~ dnorm(mu0,pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  mu0 ~ dnorm(50,pow(7.5,-2))
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
}
```

```{r}
#be sure to add your added parameters to parameters.to.save
jags_sims_republican <- jags(data = jags_data_republican,
                  model.file = model,
                  parameters.to.save = c("beta","sigma2_beta","p","sigma2_y"),
                  n.iter = 1000)

jags_sims_not_republican <- jags(data = jags_data_not_republican,
                  model.file = model,
                  parameters.to.save = c("beta","sigma2_beta","p","sigma2_y"),
                  n.iter = 1000)
```

```{r}
Calc1 <- function(myDat) # myDat is matrix with 3 cols of n, mean, and SD
{
  m = nrow(myDat)  # number of groups
  tn = 0
  tx = 0
  txx = 0
  for(i in 1:m)
  {
    n = myDat[i,1]
    mean = myDat[i,2]
    sd = myDat[i,3]
    x = n * mean
    xx = sd^2*(n - 1) + x^2 / n 
    out<-cat("grp",i," n=",n," mean=",mean," SD=", sd, " Ex=", x, " Exx=",xx, "\n")
    tn = tn + n
    tx = tx + x
    txx = txx + xx
  }
  tmean = tx / tn
  tsd = sqrt((txx - tx^2/tn) / (tn - 1))
  out <- cat("Combined","n=",tn," mean=",tmean," SD=", tsd, " Ex=", tx, " Exx=",txx,"\n")
  c(tn,tmean,tsd)
}
```


```{r}
republican_df <- data.frame(jags_sims_republican$BUGSoutput$summary)[1:56,] %>% select(n.eff,mean,sd)

binary_pref_republican <- ifelse(republican_df$mean >50, 1,0)
republican_stats <- Calc1(data.matrix(republican_df))

not_republican_df <- data.frame(jags_sims_not_republican$BUGSoutput$summary)[1:56,] %>% select(n.eff,mean,sd)

binary_pref_not_republican <- ifelse(not_republican_df$mean >50, 1,0)
not_republican_stats <- Calc1(data.matrix(not_republican_df))
```

```{r}
conf_int <- function(mean,sd,n) {
  error <- qnorm(0.975)*sd/sqrt(n)
  return(c(mean-error,mean+error))
}
#trump predictions
republican_stats[2]
conf_int(republican_stats[2],republican_stats[3],republican_stats[1])

#biden predictions
not_republican_stats[2]
conf_int(not_republican_stats[2], not_republican_stats[3],not_republican _stats[1])

```
