library(brms)
var1 <- readRDS("whovotes_model_01var.rda.rds")
var001<- readRDS("whovotes_model_strongest.rda.rds")
png(file = "var1_mixing.png")
plot(var1)
dev.off()
png(file = "var001_mixing.png")
plot(var001)
dev.off()
png(file = "var1_ppcheck.png")
brms::pp_check(var1)
dev.off()
png(file = "var001_ppcheck.png")
brms::pp_check(var001)
dev.off()
brms::LOO(var1, var001)
